title: To Be Determined
author: Alexis Olson
description: >-
  A personal blog by Alexis Olson. Thoughts, experiments, and things I'm working on.
  
# Theme from GitHub Pages Themes
remote_theme: pages-themes/slate@v0.2.0

# Enable GitHub Pages remote themes
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge
