title: Adventures in Analysis
author: Alexis Olson
description: An exploration in math, analytics, code, and BI 

# Theme from GitHub Pages Themes
remote_theme: pages-themes/slate@v0.2.0

# Enable GitHub Pages remote themes
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge
